# Generated by Django 3.1.2 on 2021-02-16 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compteBancaire', '0002_auto_20210215_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='operations',
        ),
        migrations.RemoveField(
            model_name='client',
            name='accounts',
        ),
        migrations.AddField(
            model_name='account',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='comptes', to='compteBancaire.Client'),
        ),
        migrations.AddField(
            model_name='operations',
            name='account_id',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='compteBancaire.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(db_column='solde', default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.AutoField(db_column='code', default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='NoClient',
            field=models.CharField(db_column='CIN', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='firstName',
            field=models.CharField(db_column='prenom', max_length=100),
        ),
        migrations.AlterField(
            model_name='operations',
            name='id_op',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='account',
            table='accounts',
        ),
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
        migrations.AlterModelTable(
            name='operations',
            table='operations',
        ),
    ]
