# Generated by Django 3.1.2 on 2021-02-16 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compteBancaire', '0003_auto_20210216_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operations',
            old_name='account_id',
            new_name='account',
        ),
    ]
