# Generated by Django 3.1.2 on 2021-02-16 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compteBancaire', '0004_auto_20210216_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='lastname',
        ),
    ]
