# Generated by Django 3.1.2 on 2021-02-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compteBancaire', '0005_auto_20210216_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='clients',
            field=models.ManyToManyField(related_name='comptes', to='compteBancaire.Client'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.AutoField(db_column='code', primary_key=True, serialize=False),
        ),
    ]
