# Generated by Django 3.1.2 on 2021-02-16 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compteBancaire', '0006_auto_20210217_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='compteBancaire.account'),
        ),
    ]
