# Generated by Django 3.1.2 on 2021-02-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compteBancaire', '0007_auto_20210217_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='type',
            field=models.CharField(choices=[('D', 'D'), ('C', 'C')], default='D', max_length=1),
        ),
    ]
